from pydantic import BaseModel, EmailStr, Field, ValidationError, field_validator
from string import punctuation
import re

class BankClient(BaseModel):
    username: str
    email: EmailStr
    password: str = Field(
        default=None,
        min_length= 8,
        max_length=12,
    )
    name: str

    model_config = {
        "json_schema_extra": {
            "examples": [{
                "username": "@yashu",
                "email": "yashu.ranparia@simformsolutions.com",
                "password": "********",
                "name": "Yashu",
            }]
        },

        # REMEMBER: The below field 'my_data' will not going to be included in the JSON Schema generated by openAPI, because there is no such configuration key named "my_data".
        "my_data": {
            "public_key": "TheTree12345",
        }
    }

class BankClientUpdate(BankClient):
    username: str = None
    email: EmailStr = None
    password: str = Field(
        default=None,
        min_length= 8,
        max_length=12,
    )
    name: str = None


class UserBase(BaseModel):
    username: str
    email: EmailStr
    first_name: str | None
    last_name: str | None

        

class UserRegistration(UserBase):
    password: str = Field(
        description="Must contain at least 1 uppercase, 1 lowercase and 1 special character.",
        default=None,
        min_length= 8,
        max_length=12,
    )

    @field_validator('password')
    @classmethod
    def validate_password(cls, value: str):
        special_chars = set(punctuation)
        has_special_char = False
        has_uppercae = bool(re.search('[A-Z]', value))
        has_lowercase = bool(re.search('[a-z]', value))
        for c in value:
            if c in special_chars:
                has_special_char = True
                break


        if has_special_char and has_lowercase and has_uppercae:
            return value
        
        raise ValueError("Invalid password!")
        
class UserRegistrationResponse(UserBase):
    pass